services:
  - type: web
    name: safeflow-ai
    runtime: python
    buildCommand: pip install -r requirement.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --app-dir backend
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        value: "admin@safeflow.ai"
      - key: ADMIN_PASSWORD
        sync: false
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: NEWS_API_KEY
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_VERIFY_SID
        sync: false
      - key: NVIDIA_API_KEY
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: FIREBASE_API_KEY
        sync: false
      - key: FIREBASE_AUTH_DOMAIN
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_APP_ID
        sync: false
      - key: FIREBASE_MESSAGING_SENDER_ID
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT_BASE64
        sync: false
